version: "2"
services:
  localization-rest:
    container_name: backend
    image: registry.eduix.fi/library/localization-rest-api:0.0.4
    ports:
      - "28881:28881"
    restart: always
    volumes:
      - "./localization-rest/application.properties:/opt/localization/application.properties"
    working_dir: /opt/localization
  frontend:
    links:
      - "localization-rest:restapi"
    image: frontend:1.2
    ports:
      - "3008:3000"
    restart: always
    stdin_open: true
