export const authorizedUserTypes = {
  REQUEST_AUTHORIZED_USER_FAILD: "REQUEST_AUTHORIZED_USER_FAILD",
  REQUEST_AUTHORIZED_USER_PENDING: "REQUEST_AUTHORIZED_USER_PENDING",
  REQUEST_AUTHORIZED_USER_SUCCESS: "REQUEST_AUTHORIZED_USER_SUCCESS",
};
