export const SideBarTypes = {
  HANDLE_CHANGE: "HANDLE_CHANGE",
  SET_LANGUAGES: "SET_LANGUAGES",
  SET_LOCALE_KEY: "SET_LOCALE_KEY",
  HANDLE_ADD_LANGUAGE_MODAL: "HANDLE_ADD_LANGUAGE_MODAL",
  HANDLE_ADD_LOCALE_KEY_MODAL: "HANDLE_ADD_LOCALE_KEY_MODAL",
};
