export const LocalizationTypes = {
  SET_ORG_PARAMS: "SET_ORG_PARAMS",
  SET_PRO_PARAMS: "SET_PRO_PARAMS",
  CLEAN_PRODUCTS: "CLEAN_PRODUCTS",
  HANDLE_EDIT_MODAL: "HANDLE_EDIT_MODAL",
  REQUEST_PRODUCT_FAILED: "REQUEST_PRODUCT_FAILED",
  REQUEST_PRODUCT_PENDING: "REQUEST_PRODUCT_PENDING",
  REQUEST_PRODUCT_SUCCESS: "REQUEST_PRODUCT_SUCCESS",
};
